import {
  LayoutDashboard,
  Wallet,
  Briefcase,
  Flag,
  ShieldCheck,
  Users,
  FolderKanban,
  ScrollText,
  Scale,
  ChartNoAxesCombined,
  Store,
} from "lucide-react";
export const ADMIN_NAV_ITEMS = [
  {
    href: "/admin",
    label: "Dashboard",
    icon: LayoutDashboard,
    description: "An overview of your admin workspace.",
  },
  {
    href: "/admin/financial",
    label: "Transactions",
    icon: Wallet,
    description: "Monitor verified payment activity when connected.",
  },
  {
    href: "/admin/jobs",
    label: "Job Monitoring",
    icon: Briefcase,
    description: "Monitor jobs, participants, budgets, and delivery status.",
  },
  {
    href: "/admin/reports",
    label: "Reports",
    icon: Flag,
    description: "Review evidence, record findings, and resolve reports.",
  },
  {
    href: "/admin/verification",
    label: "Verification",
    icon: ShieldCheck,
    description: "Review submitted identity and address documents.",
  },
  {
    href: "/admin/users",
    label: "Users",
    icon: Users,
    description: "Inspect platform users and roles.",
  },
  {
    href: "/admin/services",
    label: "Services",
    icon: Store,
    description: "Inspect and moderate services.",
  },
  {
    href: "/admin/projects",
    label: "Projects",
    icon: FolderKanban,
    description: "Monitor projects and contracts.",
  },
  {
    href: "/admin/audit",
    label: "Audit history",
    icon: ScrollText,
    description: "Review recorded administrator actions.",
  },
  {
    href: "/admin/disputes",
    label: "Disputes",
    icon: Scale,
    description: "Review project disputes and resolution evidence.",
  },
  {
    href: "/admin/analytics",
    label: "Analytics",
    icon: ChartNoAxesCombined,
    description: "Explore platform activity and project outcomes.",
  },
] as const;
